### ISSUE TITLE
文件大于20M上传抽风

### ISSUE THREAD

**Issue by wangyaojiu** [huanghaozi/file2link#2]
我记得JSdelivr加速限制在20M 我就上传了个20M以上的图 但是他就不停上传

**Comment by huanghaozi** [comment]
奥对，50M以上直接GG

**Comment by huanghaozi** [comment]
我的辣鸡代码没有设限

**Comment by huanghaozi** [comment]
这个repo我鸽了挺久.....唔，近期还是没啥时间，等有时间了我完善完善叭

**Comment by wangyaojiu** [comment]
我发现了个新的问题就是记得修改**Nginx缓冲区大小** 传递的参数超过接受参数的大小,会出现异常，client_body_buffer_size的值调整为51000K（jd cdn加速的最大限制是50m）这样就不会出错啦

**Comment by huanghaozi** [comment]
> 我发现了个新的问题就是记得修改**Nginx缓冲区大小** 传递的参数超过接受参数的大小,会出现异常，client_body_buffer_size的值调整为51000K（jd cdn加速的最大限制是50m）这样就不会出错啦

Mark
