### ISSUE TITLE
同时上传多个文件有的内容会改变

### ISSUE THREAD

**Issue by lcmqlcmq** [huanghaozi/file2link#3]
有的几kb的文件会变成几M。这个只能上图片吗？

**Comment by huanghaozi** [comment]
我试了试，应该不会几KB变几M叭，这个支持格式可能有些限制，除了图片应该还能传压缩包之类的，我也不清楚jsdelivr支持哪些

**Comment by huanghaozi** [comment]
可能是我整理发布源码时候的问题.....我鸽太久了....但仍然没时间，过些时日有时间我完善完善叭

**Comment by lcmqlcmq** [comment]
感觉是内容弄混了。多个文件如a的内容变成b的内容了😂

HH <notifications@github.com> 于 2020年8月14日周五 16:23写道：
